# 행렬계산하기

In [1]:
import numpy as np 

### 1. 행렬만들기(이차원(리스트안에 리스트가 있는 것) 배열을 사용하면 된다.)

##### 1-1. 일반행렬 만들기

In [4]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [5]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

##### 1-2. 랜덤행렬 만들기

In [6]:
C = np.random.rand(3, 5)
C##### 1-1. 일반행렬 만들기

array([[0.66979334, 0.92145752, 0.4353334 , 0.66260596, 0.23891962],
       [0.48025869, 0.69504257, 0.48604927, 0.2253822 , 0.35526158],
       [0.44484502, 0.92155691, 0.08192026, 0.39247496, 0.50370025]])

In [8]:
D = np.zeros((2, 4)) # 꼭 괄호를 2번 써줘야하는 것을 잊지 말것 
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 행렬에서 원소 받아오기 

In [9]:
A[0][2]

2

### 3. 행렬의 연산

In [ ]:
# 덧셈 시, 지켜야할 규칙 : 행수와 열수가 같아야함 
# 곱셈 ( 일반수 x 행렬)
# 행렬에서는 일반적인 수를 스칼라라고 함 그래서 스칼라 곱이라고 함 
# 곱셈 ( 행렬 x 행렬 )(내행렬, 외행렬)
# 

In [15]:
A = np.array([
    [1, 2, -1],
    [1, 1, -3],
    [1, 1, -3]
])

In [16]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

In [24]:
2 * A

array([[ 2,  4, -2],
       [ 2,  2, -6]])

In [23]:
A @ B + 5

array([[ -2,  10],
       [-11,   3]])

머신러닝 개념정리 : https://daje0601.tistory.com/66
선형대수학 개념정리: https://daje0601.tistory.com/67
미분 개념정리 : https://daje0601.tistory.com/69